<Project Sdk="Dalamud.NET.Sdk/15.0.0">

    <PropertyGroup>
        <Authors>Gerry of Ravine</Authors>
        <Version>1.0.3.1</Version>
        <Description>Plugin to sync Emotes across clients.</Description>
        <PackageProjectUrl>https://github.com/RaylaValdez/SimonSays</PackageProjectUrl>
        <Deterministic>true</Deterministic>
        <OutputPath>bin\$(Configuration)\</OutputPath>
    </PropertyGroup>

    <PropertyGroup>
        <TargetFramework>net10.0-windows</TargetFramework>
        <Platforms>x64</Platforms>
        <Nullable>enable</Nullable>
        <LangVersion>latest</LangVersion>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
        <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
        <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
        <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
    </PropertyGroup>

    <PropertyGroup>
        <DalamudLibPath>$(AppData)\XIVLauncher\addon\Hooks\dev\</DalamudLibPath>
        <DalamudApiLevel>15</DalamudApiLevel>
    </PropertyGroup>

    <ItemGroup>
        <Content Include="SimonSays.json">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
        <Content Include="ts500.png">
            <CopyToOutputDirectory>Always</CopyToOutputDirectory>
        </Content>
    </ItemGroup>

</Project>
